
trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  solutionName: 'Stendhal.sln'
  androidProject: 'Stendhal.Client.mobile/Stendhal.Client.mobile.Android/Stendhal.Client.mobile.Android.csproj'
  
jobs:

- job: BuildAndroid
  displayName: "Build Android App"

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solutionName)'

  - task: XamarinAndroid@1
    inputs:
      projectFile: '$(androidProject)'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'


- job: BuildiOS
  displayName: "Build iOS App"
  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solutionName)'
      
  - task: XamariniOS@2
    inputs:
      solutionFile: '$(solutionName)'
      configuration: '$(buildConfiguration)'
      packageApp: false
      buildForSimulator: true
      runNugetRestore: false

- job: RunTests
  displayName: "Run unit tests"
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'StendhalTest/StendhalTest.csproj'
      configuration: '$(buildConfiguration)'
